slant/feed/urls.py
from django.conf.urls import url

from . import views

app_name = 'feed'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

slant/slant/urls.py
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve as dj_static_serve

import dataviz.views as dv

urlpatterns = [
    url(r'^$', dv.index),
    #url(r'^admin/', admin.site.urls),
    url(r'^dataviz/', include('dataviz.urls')),
    url(r'^feed/', include('feed.urls')),
    #url(r'^news/', include('stories.urls')),
    url(r'^comics/', include('comics.urls')),
    url(r'^andrewmilligan/', include('portfolio.urls')),
    url(r'^static/(?P<path>.*)$', dj_static_serve,
      {'document_root': settings.STATIC_ROOT}),
    url(r'^', include('general.urls')),
]

slant/stories/urls.py
from django.conf.urls import url

from . import views

app_name = 'stories'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^new/$', views.check_for_new, name='check_for_new'),
    ]

slant/stories/models.py
from __future__ import unicode_literals
from django.db import models, IntegrityError
from django.utils import timezone
import json

import npr_api

# Create your models here.

class Image(models.Model):
  src = models.URLField(default='')
  caption = models.TextField(default='', null=True)
  provider = models.CharField(max_length=200, default='', null=True)
  producer = models.CharField(max_length=200, default='', null=True)
  copyright = models.CharField(max_length=200, default='', null=True)
  crop_standard_src = models.URLField(default='', null=True)
  crop_square_src = models.URLField(default='', null=True)
  crop_wide_src = models.URLField(default='', null=True)
  crop_enlargement_src = models.URLField(default='', null=True)
  crop_custom_src = models.URLField(default='', null=True)


class PullQuote(models.Model):
  text = models.TextField(default='')
  person = models.CharField(max_length=200, default='', null=True)

  def __unicode__(self):
    return self.text


class Story(models.Model):
  title = models.CharField(max_length=200, default='', unique=True)
  teaser = models.TextField(default='')
  story_date = models.DateTimeField('date published',
      default=timezone.now, null=True)
  byline = models.TextField(default='', null=True)
  text = models.TextField(default='')
  creation_date = models.DateTimeField('datetime downloaded',
      default=timezone.now)
  outlet = models.CharField(max_length=200,default='')
  images = models.ManyToManyField(Image)
  pull_quotes = models.ManyToManyField(PullQuote)

  def __unicode__(self):
    return self.title.encode('ascii', 'ignore')

  def bylineName(self):
    return json.loads(self.byline)[0]['name']['$text']

  def primaryImage(self):
    ret = None
    img_list = self.images.all()
    if img_list:
      ret = img_list[0]
    return ret

  def storyDateString(self):
    return self.story_date.strftime("%B %d, %Y")

  def storyTimeString(self):
    return self.story_date.strftime("%H:%M %p %Z")

  @classmethod
  def check_for_new(cls):
    success = False

    bot = npr_api.NPRAPIBot()
    stories = bot.getNewsStories()

    if stories:
      success = True

      for story in stories:
        images = []
        for img in story.images:
          i = Image(src = img.src,
                    caption = img.caption,
                    provider = img.provider,
                    producer = img.producer,
                    copyright = img.copyright,
                    crop_standard_src = img.crop_standard_src,
                    crop_square_src = img.crop_square_src,
                    crop_wide_src = img.crop_wide_src,
                    crop_enlargement_src = img.crop_enlargement_src,
                    crop_custom_src = img.crop_custom_src
                    )
          try:
            i.save()
          except IntegrityError as e:
            continue
          images.append(i)

        quotes = []
        for quote in story.pull_quotes:
          q = PullQuote(text = quote.text,
                        person = quote.person)
          try:
            q.save()
          except IntegrityError as e:
            continue
          quotes.append(q)

        s = Story(title = story.title,
                  teaser = story.teaser,
                  story_date = story.story_date,
                  byline = story.byline,
                  text = story.text,
                  creation_date = story.creation_date,
                  outlet = "NPR")

        try:
          s.save()
        except IntegrityError as e:
          for i in images:
            i.delete()
          for q in quotes:
            q.delete()
          continue

        for i in images:
          s.images.add(i)

        for q in quotes:
          s.pull_quotes.add(q)

    return success

slant/stories/npr_api/models.py
class Story():
  def __init__(self, **kwargs):
    self.title = ''
    self.teaser = ''
    self.story_date = None
    self.byline = ''
    self.text = ''
    self.creation_date = None
    self.images = []
    self.pull_quotes = []

  def __str__(self):
    return self.title


class Image():
  def __init__(self, **kwargs):
    self.src = ''
    self.caption = ''
    self.provider = ''
    self.producer = ''
    self.copyright = ''
    self.crop_standard_src = None
    self.crop_square_src = None
    self.crop_wide_src = None
    self.crop_enlargement_src = None
    self.crop_custom_src = None


class PullQuote():
  def __init__(self, **kwargs):
    self.text = ''
    self.person = ''

  def __unicode__(self):
    return self.text
  

slant/stories/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Story

# Create your views here.

#@login_required
def index(request):
  image_stories_list = Story.objects.filter(
      images__isnull=False).distinct().order_by('-creation_date')
  no_image_stories_list = Story.objects.filter(
      images__isnull=True).distinct().order_by('-creation_date')
  context = { 'image_stories_list': image_stories_list,
               'no_image_stories_list': no_image_stories_list }
  return render(request, 'stories/index.html', context)

#@login_required
def detail(request, pk):
  story = get_object_or_404(Story, pk=pk)
  return render(request, 'stories/detail.html', {'story': story})

#@login_required
def check_for_new(request):
  Story.check_for_new()
  return redirect('stories:index')

slant/stories/templates/stories/base.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Slant: News{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{% static 'stories/style.css' %}">
{% endblock %}

{% block navbar_stories_class %}{% endblock %}

{% block content %}{% endblock %}

slant/stories/templates/stories/detail.html
{% extends "stories/base.html" %}

{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{% static 'stories/story_detail.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'stories/style.css' %}">
{% endblock %}

{% block content %}
  <div class="story">

    <div class="story-title">
      <h1 id="story-title" class="page-header">{{ story.title }}</h1>
    </div>

    <div class="story-info">
      {% if story.story_date %}
        <p>{{ story.storyDateString }} &bull; {{ story.storyTimeString }}</p>
      {% endif %}
      {% if story.byline %}
        <p>{{ story.bylineName }}</p>
      {% endif %}
    </div>

    {% if not story.primaryImage is None %}
      <div class="story-image">
        <div class="imagewrap">
          <img src="{{ story.primaryImage.crop_wide_src }}" class="img" width="100%">
        </div>
        <div class="credit-caption">
          <div class="image-caption">
            <p>{{ story.primaryImage.caption }}</p>
          </div>
          <span class="image-credit">
            {% if story.primaryImage.producer %}
              {{ story.primaryImage.producer }}
              {% if story.primaryImage.provider %}
                /{{ story.primaryImage.provider }}
              {% endif %}
            {% else %}
              {% if story.primaryImage.provider %}
                {{ story.primaryImage.provider }}
              {% endif %}
            {% endif %}
          </span>
        </div>
      </div>
    {% endif %}

    {% if not story.pull_quotes is None  and story.pull_quotes %}
      {% for quote in story.pull_quotes.all %}
        <div class="storyquote">
          <p><blockquote>{{ quote.text }}</blockquote></p>
          <p><small>{{ quote.person }}<small></p>
        </div>
      {% endfor %}
    {% endif %}

    <div class="storybody">
      {% autoescape off %}
      {{ story.text }}
      {% endautoescape %}
    </div>

  </div>

  <!--
  <div class="backbutton">
    <p><a class="btn btn-default" href="{% url 'stories:index' %}" role="button">Back</a>
  </div>
  -->

{% endblock %}

slant/stories/templates/stories/index.html
{% extends "stories/base.html" %}
{% load static %}
  
{% block content %}

  <div class="col-md-8">
  {% if image_stories_list or no_image_stories_list %}
    
    {% if image_stories_list %}
      {% for story in image_stories_list %}

        <div class="row">
          <div class="col-md-12">
            <div class="storybox">

              {% if not story.primaryImage is None %}
                <div class="storybox-image">
                  <div class="imagewrap">
                    <img src="{{ story.primaryImage.crop_wide_src }}" class="img" width="100%">
                  </div>
                  <div class="credit-caption">
                    <span class="image-credit">
                      {% if story.primaryImage.producer %}
                        {{ story.primaryImage.producer }}
                        {% if story.primaryImage.provider %}
                          /{{ story.primaryImage.provider }}
                        {% endif %}
                      {% else %}
                        {% if story.primaryImage.provider %}
                          {{ story.primaryImage.provider }}
                        {% endif %}
                      {% endif %}
                    </span>
                  </div>
                </div>
              {% endif %}

              <div class="storybox-info">
                <h4 class="outlet-slug">{{ story.outlet }}</h4>
                <h3><a href="{% url 'stories:detail' story.id %}">{{ story.title }}</a></h3>
                <div class="storybox-teaser">
                  <span class="date">{{ story.storyDateString }} &bull;</span>
                  {% autoescape off %}
                  {{ story.teaser }}
                  {% endautoescape %}
                </div>
              </div>

            </div>
          </div>
        </div>

      {% endfor %}
    {% endif %}

    {% if no_image_stories_list %}
      <div class="row">
        {% for story in no_image_stories_list %}

            <div class="col-md-6">
              <div class="storybox">

                <div class="storybox-info noimage">
                  <h4 class="outlet-slug">{{ story.outlet }}</h4>
                  <h3><a href="{% url 'stories:detail' story.id %}">{{ story.title }}</a></h3>
                  <div class="storybox-teaser">
                    <span class="date">{{ story.storyDateString }} &bull;</span>
                    {{ story.teaser }}
                  </div>
                </div>

              </div>
            </div>

            {% if forloop.counter|divisibleby:2 %}
      </div>
      <div class="row">
            {% endif %}

        {% endfor %}
        </div>

    {% endif %}

  {% else %}
    <div class="storybox" id="nothingnew">
      <h2>No new stories.</h2>
    </div>
  {% endif %}

  </div>

  <div class="col-md-4">
    <div class="row">
      <div class="col-md-12">
        <div class="outlet-banner">

          <div class="outlet-logo">
            <img src="{% static 'stories/npr-logo.png' %}" class="img" width="100%">
          </div>

          <div class="outlet-blurb">
            <p>
            "<strong>National Public Radio</strong> will serve the individual; it
            will promote personal growth; it will regard the individual
            differences among men with respect and joy rather than derision and
            hate; it will celebrate the human experience as infinitely varied
            rather than vacuous and banal; it will encourage a sense of active
            constructive participation, rather than apathetic helplessness."
            &mdash;Bill Siemering
            </p>
          </div>

          <div class="outlet-dashboard">
            {% if user.is_authenticated %}
            <p>Stories are updated nightly, but click the button below to pull
            down new stories from NPR. Or visit the NPR website directly for
            more.</p>
            {% else %}
            <p>Stories are updated nightly, but visit the NPR website directly
            for more.</p>
            {% endif %}

            {% if user.is_authenticted %}
            <div class="dashboard-button">
              <a class="btn btn-default btn-block" href="{% url 'stories:check_for_new' %}">New Stories</a>
            </div>
            {% endif %}

            <div class="dashboard-button">
              <a class="btn btn-default btn-block" href="http://www.npr.org/">Visit NPR</a>
            </div>
          </div>

        </div>
      </div>
    </div>

  </div>

{% endblock %}