slant/feed/urls.py
from django.conf.urls import url

from . import views

app_name = 'feed'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

slant/general/urls.py
from django.conf.urls import url

from . import views

app_name = 'general'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    ]

slant/slant/urls.py
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve as dj_static_serve

import dataviz.views as dv

urlpatterns = [
    url(r'^$', dv.index),
    #url(r'^admin/', admin.site.urls),
    url(r'^dataviz/', include('dataviz.urls')),
    url(r'^feed/', include('feed.urls')),
    #url(r'^news/', include('stories.urls')),
    url(r'^comics/', include('comics.urls')),
    url(r'^andrewmilligan/', include('portfolio.urls')),
    url(r'^static/(?P<path>.*)$', dj_static_serve,
      {'document_root': settings.STATIC_ROOT}),
    url(r'^', include('general.urls')),
]

slant/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-116096571-1"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());

			gtag('config', 'UA-116096571-1');
		</script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Slant{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="stylesheet" href="{% static 'base/style.css' %}">

    {% block stylesheets %}
    {% endblock %}

    {#<link rel="icon" href="{% block favicon %}{% static 'base/slantedlabs_logo_noback.png' %}{% endblock %}">#}
    <link rel="icon" href="{% block favicon %}{% static 'base/slantedlabs_logo_y2_crop_noback.png' %}{% endblock %}">

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<img src="{% static 'base/slant_favicon_red.svg' %}" width=50>-->
          <img src="{% static 'base/slantedlabs_logo_y2_crop_noback.png' %}" width=50>
          <a class="navbar-brand" href="/">Slant</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <span class="navbar-brand-tag">
            Pointed investigation of enlightening data.
          </span>

          <ul class="nav navbar-nav navbar-right">
            <li class="{% block navbar_about_class %}{% endblock %}">
              <a href="{% url 'general:about' %}">About</a>
            </li>
            <li>
              <a href="https://twitter.com/slantedlabs" target="_blank">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
            </li>
            <li>
              <a href="https://github.com/slantedlabs" target="_blank">
                <i class="fa fa-github" aria-hidden="true"></i>
              </a>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block rawcontent %}
    <div class="container contentblock-container">
      {% block content %}{% endblock %}
    </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block scripts %}
    {% endblock %}

  </body>

</html>