slant/dataviz/urls.py
from django.conf.urls import url

from . import views

app_name = 'dataviz'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[a-zA-Z0-9-_]+)/$', views.detail, name='detail'),
    ]

slant/feed/urls.py
from django.conf.urls import url

from . import views

app_name = 'feed'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

slant/portfolio/urls.py
from django.conf.urls import url

from . import views

app_name = 'portfolio'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[a-zA-Z0-9-_]+)/$', views.detail, name='detail'),
    ]

slant/slant/urls.py
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve as dj_static_serve

import dataviz.views as dv

urlpatterns = [
    url(r'^$', dv.index),
    #url(r'^admin/', admin.site.urls),
    url(r'^dataviz/', include('dataviz.urls')),
    url(r'^feed/', include('feed.urls')),
    #url(r'^news/', include('stories.urls')),
    url(r'^comics/', include('comics.urls')),
    url(r'^andrewmilligan/', include('portfolio.urls')),
    url(r'^static/(?P<path>.*)$', dj_static_serve,
      {'document_root': settings.STATIC_ROOT}),
    url(r'^', include('general.urls')),
]

slant/portfolio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Project(models.Model):
  slug = models.CharField(max_length=200, default='')
  title = models.CharField(max_length=200, default='', unique=True)
  teaser = models.TextField(default='')
  text = models.TextField(default='')
  image = models.TextField(default='')
  rank = models.IntegerField(null=True)

  def __unicode__(self):
    return self.title.encode('ascii', 'ignore')

slant/portfolio/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Project

# Create your views here.

#@login_required
def index(request):
  proj_list = Project.objects.all().order_by('rank')
  context = { 'projects_list': proj_list }
  return render(request, 'portfolio/splash.html', context)

#@login_required
def detail(request, slug):
  project = get_object_or_404(Project, slug=slug)
  context = {
      'project': project,
      }
  return render(request, 'portfolio/detail.html', context)

slant/portfolio/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Slant{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    {% load static %}
    <!--<link rel="stylesheet" href="{% static 'base/style.css' %}">-->
    <link rel="stylesheet" href="{% static 'portfolio/navbar_transparent.css' %}">

    {% block stylesheets %}
    {% endblock %}

    {#<link rel="icon" href="{% block favicon %}{% static 'base/slantedlabs_logo_noback.png' %}{% endblock %}">#}
    <link rel="icon" href="{% block favicon %}{% static 'base/slantedlabs_logo_y2_crop_noback.png' %}{% endblock %}">

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-transparent navbar-simple navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'portfolio:index' %}">Andrew Milligan</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="https://twitter.com/slantedlabs" target="_blank">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
            </li>
            <li>
              <a href="https://github.com/andrewmilligan" target="_blank">
                <i class="fa fa-github" aria-hidden="true"></i>
              </a>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block rawcontent %}
    <div class="container contentblock-container">
      {% block content %}{% endblock %}
    </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block scripts %}
    {% endblock %}

  </body>

</html>

slant/portfolio/templates/portfolio/detail.html
{% extends "portfolio/base.html" %}

{% load static %}
{% load dataviz_tags %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'portfolio/project_detail.css' %}">
{% endblock %}

{% block content %}
  <div class="story">

    <div class="story-title">
      <h1 id="story-title" class="page-header">{{ project.title }}</h1>
    </div>

    <div class="storybody text">
      {% render_this project.text %}
    </div>

    <div class="storyend">
      <img src="{% static 'base/slant_favicon_333.svg' %}">
    </div>

    <div class="backbutton">
      <p><a class="btn btn-default" href="{% url 'portfolio:index' %}" role="button">
        <span class="glyphicon glyphicon-menu-left"></span>
        <span class="glyphicon glyphicon-menu-left"></span>
        <span class="glyphicon glyphicon-menu-left"></span></a>
      </p>
    </div>
  </div>


{% endblock %}

slant/portfolio/templates/portfolio/index.html
{% extends "dataviz/base.html" %}
{% load static %}
{% load dataviz_tags %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'base/outlet_banner.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dataviz/storybox.css' %}">
{% endblock %}
  
{% block content %}

  <div class="col-md-8">
  {% if stories_list %}
    
    {% for story in stories_list %}

      <div class="row">
        <div class="col-md-12">
          <div class="storybox">

            {% if story.primaryImage %}
            <div class="storybox-image">
              <div class="imagewrap">
                <img src="{% static story.primaryImage %}" class="img" width="100%">
              </div>
            </div>
            {% endif %}

            <a href="{% url 'dataviz:detail' story.slug %}">
              <div class="storybox-info">
                <h4 class="outlet-slug">{{ story.outlet }}</h4>
                <h3 class="story-title">{{ story.title }}</h3>
                <div class="storybox-teaser">
                  {% if story.story_date %}
                    <div class="date">{{ story.storyDateString }} &bull;</div>
                  {% endif %}
                  {% render_this story.teaser %}
                </div>
              </div>
            </a>

          </div>
        </div>
      </div>

    {% endfor %}

  {% else %}
    <div class="storybox" id="nothingnew">
      <h2>No new stories.</h2>
    </div>
  {% endif %}
  </div>


  <div class="col-md-4">
    <div class="row">
      <div class="col-md-12">
        <div class="outlet-banner">

          <div class="outlet-logo">
            <img src="{% static 'base/slant_favicon_red.svg' %}" class="img" width="50%">
          </div>

          <div class="outlet-blurb">
            <p class="lead text-special">
            <strong>Slant</strong> is my own thing and only reflects my own
            opinions&mdash;my own slant. These are mostly small data
            visualization projects that I have done for fun just because they
            seemed interesting at the time.
            </p>
          </div>

        </div>
      </div>
    </div>

  </div>

{% endblock %}

slant/portfolio/templates/portfolio/splash.html
{% extends "portfolio/base.html" %}
{% load static %}
{% load dataviz_tags %}

{% block title %}Andrew Milligan{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'portfolio/splash.css' %}">
{% endblock %}
  
{% block rawcontent %}

<div class="portfolio">

  <div class="container-fluid project-container portfolio-intro">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="portfolio-intro">
          Welcome to my portfolio.
        </h1>
        <div class="next-indicator">
          <i class="fa fa-angle-down" aria-hidden="true"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      {% for proj in projects_list %}
      <a href="{% url 'portfolio:detail' slug=proj.slug %}">
        <div class="col-xs-12 col-md-4 project-container" style="background-image: url({% static proj.image %});">
          <h1 class="project-title">{{ proj.title }}</h1>
          <p class="lead project-teaser">{{ proj.teaser }}</p>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>

</div>

<script>
window.onscroll = function() { foo(); }
function foo() {
  console.log("hello world");
}
</script>

{% endblock %}