slant/comics/urls.py
from django.conf.urls import url

from . import views

app_name = 'comics'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^last/$', views.check_for_new, name='check_for_new'),
    url(r'^random/$', views.get_random, name='get_random'),
    ]

slant/feed/urls.py
from django.conf.urls import url

from . import views

app_name = 'feed'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

slant/slant/urls.py
from . import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve as dj_static_serve

import dataviz.views as dv

urlpatterns = [
    url(r'^$', dv.index),
    #url(r'^admin/', admin.site.urls),
    url(r'^dataviz/', include('dataviz.urls')),
    url(r'^feed/', include('feed.urls')),
    #url(r'^news/', include('stories.urls')),
    url(r'^comics/', include('comics.urls')),
    url(r'^andrewmilligan/', include('portfolio.urls')),
    url(r'^static/(?P<path>.*)$', dj_static_serve,
      {'document_root': settings.STATIC_ROOT}),
    url(r'^', include('general.urls')),
]

slant/comics/models.py
from __future__ import unicode_literals

from django.db import models

import xkcd_api
import random

# Create your models here.

class Comic(models.Model):
  title = models.CharField(max_length=200, default='')
  image_src = models.URLField(default='')
  hover_text = models.TextField(null=True)
  outlet = models.CharField(max_length=200, default='', null=True)
  num = models.IntegerField(null=True)

  @classmethod
  def check_for_new(cls):
    bot = xkcd_api.XkcdAPIBot()
    comic = bot.getCurrentComic()
    success = False
    if not comic is None:
      success = True
      cls.objects.all().delete()
      c = cls(title = comic.title,
              image_src = comic.image_src,
              hover_text = comic.hover_text,
              num = comic.num,
              outlet = comic.outlet)
      c.save()
      return c
    return None

  @classmethod
  def get_random(cls):
    bot = xkcd_api.XkcdAPIBot()
    # get current comic to find max num. Min num is 1
    newest_comic = bot.getCurrentComic()
    if not newest_comic is None:
      i = random.randrange(1, newest_comic.num + 1)
      comic = bot.getComicNum(i)
      if not comic is None:
        cls.objects.all().delete()
        c = cls(title = comic.title,
                image_src = comic.image_src,
                hover_text = comic.hover_text,
                num = comic.num,
                outlet = comic.outlet)
        c.save()
        return c
    return None

slant/comics/xkcd_api/models.py
class Comic():
  def __init__(self, **kwargs):
    self.title = ''
    self.image_src = ''
    self.hover_text = ''
    self.outlet = ''
    self.num = 0

  def __unicode__(self):
    return self.title
  

slant/comics/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Comic

# Create your views here.

#@login_required
def index(request):
  comic = Comic.check_for_new()
  comic = Comic.objects.all().first()
  return render(request, 'comics/index.html', {'comic': comic})

#@login_required
def check_for_new(request):
  comic = Comic.check_for_new()
  return render(request, 'comics/comic.html', {'comic': comic})

#@login_required
def get_random(request):
  comic = Comic.get_random()
  return render(request, 'comics/comic.html', {'comic': comic})

slant/comics/templates/comics/adbox.html
{% load static %}
<a href="{% url 'comics:index' %}" class="no-change">
  <div class="adbox">
    <div class="container adbox-body">
      <div class="row">
        <div class="adbox-content">
          <div class="adbox-img-wrapper">
            <img class="img" src="{% static 'comics/xkcd_banner_crop_adbox.png' %}" width=100%>
          </div>
        </div>
      </div>
    </div>
  </div>
</a>

slant/comics/templates/comics/base.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Slant: Comics{% endblock %}

{% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{% static 'comics/style.css' %}">
{% endblock %}

{% block navbar_comics_class %}{% endblock %}

{% block content %}{% endblock %}

{% block scripts %}{% endblock %}

slant/comics/templates/comics/comic.html
<div class="comic-title">
  <h2>{{ comic.title }}</h2>
</div>
<div class="comic-image">
  <img src="{{ comic.image_src }}" class="comic"
    title="{{ comic.hover_text }}">
</div>

slant/comics/templates/comics/index.html
{% extends 'comics/base.html' %}
{% load static %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'base/outlet_banner.css' %}">
{% endblock %}

{% block content %}

  <div class="comic-area">

    <div class="row">
      <div class="col-md-12">
        <div class="outlet-banner">
          <div class="outlet-logo">
            <a href="http://xkcd.com/"><img src="{% static 'comics/xkcd_banner_crop.png' %}" class="img" width="100%"></a>
          </div>
          <div class="outlet-blurb">
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="comic-wrapper" id="comic-wrapper">
          {% include 'comics/comic.html' with comic=comic %}
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="dashboard-button">
          <a class="btn btn-default btn-block"
            href="http://www.explainxkcd.com/{{ comic.num }}" target="_blank">Explain xkcd</a>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="dashboard-button" id="random_button" ajax-update-url="{% url 'comics:get_random' %}">
          <a class="btn btn-default btn-block" onClick="ajaxUpdateComicRandom()">
            <span class="glyphicon glyphicon-random"></span>
          </a>
        </div>
      </div>

      <div class="col-md-6">
        <div class="dashboard-button" id="latest_button" ajax-update-url="{% url 'comics:check_for_new' %}">
          <a class="btn btn-default btn-block" onClick="ajaxUpdateComicLatest()">
            <span class="glyphicon glyphicon-fast-forward"></span>
          </a>
        </div>
      </div>
    </div>

  </div>
  
{% endblock %}

{% block scripts %}
  <script>
    function ajaxUpdateComicRandom() {
      $.ajax({
        url: $("#random_button").attr("ajax-update-url"),
        data: {},
        dataType: 'html',
        success: function (data) {
          $("#comic-wrapper").html(data);
        }
      });
    }

    function ajaxUpdateComicLatest() {
      $.ajax({
        url: $("#latest_button").attr("ajax-update-url"),
        data: {},
        dataType: 'html',
        success: function (data) {
          $("#comic-wrapper").html(data);
        }
      });
    }
  </script>
{% endblock %}